services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: ui
    ports:
      - "${SWAGGER_UI_HOST_PORT}:8080"
    volumes:
      - C:\docker\swagger\openapi:/usr/share/nginx/html/oas/
    environment:
      - URLS_PRIMARY_NAME=${URLS_PRIMARY_NAME}
      - URLS=${URLS}